#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

STAMP=$(date +%Y%m%d)
PLUGIN_ROOT=""
DONE=()

# patch FILE "old text" "new text" "what it does"
# Backs the file up, makes the change, says whether it worked.
# Safe to run twice: if the change is already there, it says so and moves on.
patch() {
  local file="$1" old="$2" new="$3" label="$4"

  if [[ ! -f "$file" ]]; then
    warn "$label: file not found, skipped"
    SKIPPED+=("$label (file missing: $file)")
    return
  fi

  if grep -qF "$new" "$file" 2>/dev/null; then
    say "$label: already done"
    DONE+=("$label (was already set)")
    return
  fi

  if ! grep -qF "$old" "$file" 2>/dev/null; then
    warn "$label: could not find the line to change"
    note "The plugin may have changed. Look in: $file"
    SKIPPED+=("$label (line not found, plugin may have changed)")
    return
  fi

  [[ -f "$file.bak-$STAMP" ]] || cp "$file" "$file.bak-$STAMP"

  python3 - "$file" "$old" "$new" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
p.write_text(p.read_text().replace(sys.argv[2], sys.argv[3]))
PY

  if grep -qF "$new" "$file"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
    DONE+=("$label")
  else
    warn "$label: the change did not stick"
    SKIPPED+=("$label (write failed)")
  fi
}

banner "Codex review gate"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Find the Codex plugin"
say "Codex lives in a folder named after its version number."
say "Looking for it now."
printf '\n'

CODEX_BASE="$HOME/.claude/plugins/cache/openai-codex/codex"

if [[ ! -d "$CODEX_BASE" ]]; then
  warn "Codex is not installed here."
  note "Expected: $CODEX_BASE"
  note "Install it with: claude plugin install codex@openai-codex"
  exit 1
fi

PLUGIN_ROOT=$(find "$CODEX_BASE" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort -V | tail -n1)

if [[ -z "$PLUGIN_ROOT" || ! -f "$PLUGIN_ROOT/scripts/lib/state.mjs" ]]; then
  warn "Found the Codex folder, but not the files this wizard edits."
  note "Looked in: $CODEX_BASE"
  note "The plugin layout may have changed in a newer version."
  exit 1
fi

say "Found version $(basename "$PLUGIN_ROOT")."
note "$PLUGIN_ROOT"
printf '\n'
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Turn the review on everywhere"
say "Right now Codex only reviews the projects you switched it on for."
say "This makes it review every project instead."
say "You then switch it OFF in projects where you do not want it."
printf '\n'
note "A copy of the original file is kept next to it, ending .bak-$STAMP"
printf '\n'

patch "$PLUGIN_ROOT/scripts/lib/state.mjs" \
  "stopReviewGate: false" \
  "stopReviewGate: true" \
  "Review runs in every project"

printf '\n'
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Shorten the wait (optional)"
say "Codex currently gets 15 minutes to review before anything stops it."
say "This cuts that to 5 minutes, so a slow review stops holding you up."
printf '\n'
say "It also fixes a bug. Two limits are both set to 15 minutes: one on the"
say "review itself, one on the thing waiting for it. Because they are equal,"
say "the waiting one can kill the review before it can tell you it ran long."
say "Setting them to 5 and 7 minutes leaves room for that message."
printf '\n'

if confirm "Make both of those changes?"; then
  printf '\n'
  patch "$PLUGIN_ROOT/scripts/stop-review-gate-hook.mjs" \
    "const STOP_REVIEW_TIMEOUT_MS = 15 * 60 * 1000;" \
    "const STOP_REVIEW_TIMEOUT_MS = 5 * 60 * 1000;" \
    "Review time limit is 5 minutes"

  patch "$PLUGIN_ROOT/hooks/hooks.json" \
    '"timeout": 900' \
    '"timeout": 420' \
    "Outer time limit is 7 minutes"
else
  printf '\n'
  say "Skipped. The review keeps its 15 minute limit."
  note "Re-run this wizard any time if you change your mind."
fi

printf '\n'
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Check it worked"

CHECK_OK=1

check() {
  local file="$1" want="$2" label="$3"
  if grep -qF "$want" "$file" 2>/dev/null; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$label"
    CHECK_OK=0
  fi
}

check "$PLUGIN_ROOT/scripts/lib/state.mjs" \
  "stopReviewGate: true" "Review runs in every project"

printf '\n'

if (( CHECK_OK )); then
  say "The main change is in place."
else
  warn "The main change is NOT in place. Look at the messages above."
fi

printf '\n'
say "Two things to know:"
step "Restart Claude Code. Nothing changes until you do."
step "Updating the Codex plugin undoes all of this. Run this wizard again after"
say "  any 'claude plugin install codex@openai-codex'."
printf '\n'
say "To switch the review off in one project, run /codex:setup inside it."
printf '\n'
pause "Press Enter for the summary"

finish

if (( ${#DONE[@]} )); then
  printf '  %sChanged:%s\n' "$BOLD" "$RESET"
  for d in "${DONE[@]}"; do note "  - $d"; done
  printf '\n'
fi
